---
params:
  dt_eff: !r Sys.Date()-1
---

```{r setup, include=FALSE}
library(data.table)
library(lubridate)
library(caim)
```

```{r FuncStuff, include=FALSE}
EndOfMonth <- function(dt_eff) {
  
  dtEOM <- ceiling_date(dt_eff, 'month') %m-% days(1)
  
  if (wday(dtEOM) == 1) {
    dtEOM <- dtEOM - 2
  } else if (wday(dtEOM) == 7) {
    dtEOM <- dtEOM - 1
  }
  
  if (dt_eff >= dtEOM) {
    EOM <- TRUE
  } else {
    EOM <- FALSE
  }
  
  return(EOM)  
}

GetiIdx <- function(index, IndexList, nIdx) {
  found <- FALSE
  iIdx <- 1
  while (iIdx <= nIdx && !found) {
    if(index == IndexList$index_code[iIdx]) {
      found <- TRUE
    } else {
      iIdx <- iIdx + 1
    }
  }
  if (!found) {
    iIdx <- -1
  }
  return(iIdx)
}

GetPastAc <- function(account_id, dt_eff, past_data, nPast) {
  found <- FALSE
  iPast <- 1
  
  while (iPast <= nPast && !found) {
    if(account_id == past_data$account_id[iPast]) {
      found <- TRUE
    } else {
      iPast <- iPast + 1
    }
  }
  
  account_index <- 100
  bench_index <- 100
  no_rec <- TRUE
  
  while (iPast <= nPast && found) {
    if (account_id == past_data$account_id[iPast] && dt_eff > past_data$obs_date[iPast]) {
      account_index <- past_data$account_index[iPast]
      bench_index <- past_data$bench_index[iPast]
      iPast <- iPast + 1
    } else {
      if (account_id == past_data$account_id[iPast] && dt_eff == past_data$obs_date[iPast]) {
        no_rec <- FALSE
      }
      found <- FALSE
    }
  }
  
return(c(no_rec, account_index, bench_index))
}
```

```{r DBstuff, include=FALSE}
config <- fread(ifelse(file.exists("./config/config.csv"), "./config/config.csv", "./config/config_default.csv"))
prefs <- list()
for (x in 1:nrow(config)) {
  prefs[[config[x, parameter]]] <- config[x, value]
}
DB_HOST <- prefs$db_host
DB_NAME <- prefs$db_name
DB_USER <- prefs$db_user
DB_PASSWORD <- prefs$db_password

conn <- caim::mdb_connect(DB_USER, DB_PASSWORD, DB_HOST, DB_NAME)

ACTIVITY_PATH_ROOT <- prefs$activity_path_root
CONTACT_PATH <- prefs$contact_path
OUTLOOK_PATH_ROOT <- prefs$outlook_path_root
OUTLOOK_EMPTY_FILE <- prefs$outlook_empty_file

if (wday(params$dt_eff) == 1) {
    params$dt_eff <- params$dt_eff - 2
}

dt_1mago <- as.Date(format(params$dt_eff,"%Y-%m-01"))-7
```

```{r GetPerf, include=FALSE}
query_text <- paste0("SELECT DISTINCT id.index_code, id.obs_date, id.tot_ret_ix_loc,  
      id.tot_ret_ix_usd, id.tot_ret_ix_usd_h, id.tot_ret_ix_gbp, id.tot_ret_ix_gbp_h
  FROM mkt_ice_index_data id
  RIGHT JOIN caim_account_index cai on id.index_code = cai.index_code 
  WHERE cai.dt_start <= '",params$dt_eff,"' 
  AND (cai.dt_end >= '",params$dt_eff,"' OR cai.dt_end is NULL)
  AND id.obs_date >= '", dt_1mago, "'
  AND id.obs_date <= '", params$dt_eff, "'
  ORDER BY id.index_code, id.obs_date")
perf_data <- data.table(caim::mdb_get(conn, query_text))
```

```{r GetAcIdx, include=FALSE}
query_text <- paste0("SELECT cai.* 
  FROM caim_account_index cai
  WHERE cai.dt_start <= '",params$dt_eff,"' 
  AND (cai.dt_end >= '",params$dt_eff,"' OR cai.dt_end is NULL)
  AND calc_type != 'XDR'
  ORDER BY cai.account_id")
acidx_data <- data.table(caim::mdb_get(conn, query_text))
```

```{r CalcRtns, include=FALSE}
nperf <- length(perf_data$index_code)
if (nperf > 0) {
  old_index <- perf_data$index_code[1]
  index_data <- data.frame(matrix(nrow=0,ncol=13))
  names(index_data)<-c("index_code","mtd_rtn_usd","mtd_rtn_yest_usd","day_rtn_usd", "mtd_rtn_usd_h","mtd_rtn_yest_usd_h","day_rtn_usd_h","mtd_rtn_gbp","mtd_rtn_yest_gbp", "day_rtn_gbp","mtd_rtn_gbp_h","mtd_rtn_yest_gbp_h","day_rtn_gbp_h")
  
  for (iperf in 1:nperf) {
    
    if (perf_data$index_code[iperf] != old_index) {
      index_today_usd <- perf_data$tot_ret_ix_usd[iperf-1]
      index_yest_usd <- perf_data$tot_ret_ix_usd[iperf-2]
      index_today_usd_h <- perf_data$tot_ret_ix_usd_h[iperf-1]
      index_yest_usd_h <- perf_data$tot_ret_ix_usd_h[iperf-2]
      index_today_gbp <- perf_data$tot_ret_ix_gbp[iperf-1]
      index_yest_gbp <- perf_data$tot_ret_ix_gbp[iperf-2]
      index_today_gbp_h <- perf_data$tot_ret_ix_gbp_h[iperf-1]
      index_yest_gbp_h <- perf_data$tot_ret_ix_gbp_h[iperf-2]
  
      mtd_rtn_usd <- 100*(index_today_usd / index_prevme_usd - 1)
      mtd_rtn_yest_usd <- 100*(index_yest_usd / index_prevme_usd - 1)
      day_rtn_usd <- 100*(index_today_usd / index_yest_usd - 1)
        
      mtd_rtn_usd_h <- 100*(index_today_usd_h / index_prevme_usd_h - 1)
      mtd_rtn_yest_usd_h <- 100*(index_yest_usd_h / index_prevme_usd_h - 1)
      day_rtn_usd_h <- 100*(index_today_usd_h / index_yest_usd_h - 1)
        
      mtd_rtn_gbp <- 100*(index_today_gbp / index_prevme_gbp - 1)
      mtd_rtn_yest_gbp <- 100*(index_yest_gbp / index_prevme_gbp - 1)
      day_rtn_gbp <- 100*(index_today_gbp / index_yest_gbp - 1)
        
      mtd_rtn_gbp_h <- 100*(index_today_gbp_h / index_prevme_gbp_h - 1)
      mtd_rtn_yest_gbp_h <- 100*(index_yest_gbp_h / index_prevme_gbp_h - 1)
      day_rtn_gbp_h <- 100*(index_today_gbp_h / index_yest_gbp_h - 1)
        
      index_data[nrow(index_data)+1,] <- c(old_index, mtd_rtn_usd, mtd_rtn_yest_usd, day_rtn_usd, mtd_rtn_usd_h, mtd_rtn_yest_usd_h, day_rtn_usd_h, mtd_rtn_gbp, mtd_rtn_yest_gbp, day_rtn_gbp, mtd_rtn_gbp_h, mtd_rtn_yest_gbp_h, day_rtn_gbp_h)
        
      old_index <- perf_data$index_code[iperf]
    }

    if (month(perf_data$obs_date[iperf]) == month(dt_1mago)) {
      index_prevme_usd <- perf_data$tot_ret_ix_usd[iperf]
      index_prevme_usd_h <- perf_data$tot_ret_ix_usd_h[iperf]
      index_prevme_gbp <- perf_data$tot_ret_ix_gbp[iperf]
      index_prevme_gbp_h <- perf_data$tot_ret_ix_gbp_h[iperf]
    }
  }

  index_today_usd <- perf_data$tot_ret_ix_usd[nperf]
  index_yest_usd <- perf_data$tot_ret_ix_usd[nperf-1]
  index_today_usd_h <- perf_data$tot_ret_ix_usd_h[nperf]
  index_yest_usd_h <- perf_data$tot_ret_ix_usd_h[nperf-1]
  index_today_gbp <- perf_data$tot_ret_ix_gbp[nperf]
  index_yest_gbp <- perf_data$tot_ret_ix_gbp[nperf-1]
  index_today_gbp_h <- perf_data$tot_ret_ix_gbp_h[nperf]
  index_yest_gbp_h <- perf_data$tot_ret_ix_gbp_h[nperf-1]

  mtd_rtn_usd <- 100*(index_today_usd / index_prevme_usd - 1)
  mtd_rtn_yest_usd <- 100*(index_yest_usd / index_prevme_usd - 1)
  day_rtn_usd <- 100*(index_today_usd / index_yest_usd - 1)
  
  mtd_rtn_usd_h <- 100*(index_today_usd_h / index_prevme_usd_h - 1)
  mtd_rtn_yest_usd_h <- 100*(index_yest_usd_h / index_prevme_usd_h - 1)
  day_rtn_usd_h <- 100*(index_today_usd_h / index_yest_usd_h - 1)

  mtd_rtn_gbp <- 100*(index_today_gbp / index_prevme_gbp - 1)
  mtd_rtn_yest_gbp <- 100*(index_yest_gbp / index_prevme_gbp - 1)
  day_rtn_gbp <- 100*(index_today_gbp / index_yest_gbp - 1)
  
  mtd_rtn_gbp_h <- 100*(index_today_gbp_h / index_prevme_gbp_h - 1)
  mtd_rtn_yest_gbp_h <- 100*(index_yest_gbp_h / index_prevme_gbp_h - 1)
  day_rtn_gbp_h <- 100*(index_today_gbp_h / index_yest_gbp_h - 1)
  
  index_data[nrow(index_data)+1,] <- c(old_index, mtd_rtn_usd, mtd_rtn_yest_usd, day_rtn_usd, mtd_rtn_usd_h, mtd_rtn_yest_usd_h, day_rtn_usd_h, mtd_rtn_gbp, mtd_rtn_yest_gbp, day_rtn_gbp, mtd_rtn_gbp_h, mtd_rtn_yest_gbp_h, day_rtn_gbp_h)
}
```

```{r CalcBMs, include=FALSE}
nidx <- length(index_data$index_code)
nacidx <- length(acidx_data$account_id)

if (nacidx > 0) {
  nac <- 1
  mtd_rtn <- 0
  mtd_rtn_yest <- 0
  old_ac <- acidx_data$account_id[1]
  ac_data <- data.frame(matrix(nrow=0,ncol=5))
  names(ac_data)<-c("account_id","mtd_rtn","mtd_rtn_yest","day_rtn","calc_eom")
  
  for (iacidx in 1:nacidx) {
    iidx <- GetiIdx(acidx_data$index_code[iacidx], index_data, nidx)
    if (acidx_data$account_id[iacidx] != old_ac) {
      day_rtn = 100 * ((1 + mtd_rtn/100)/(1 + mtd_rtn_yest/100) - 1)
      ac_data[nac,] <- c(acidx_data$account_id[iacidx-1], mtd_rtn, mtd_rtn_yest, day_rtn, acidx_data$calc_eom[iacidx-1])
      nac <- nac + 1
      old_ac <- acidx_data$account_id[iacidx]
      if (iidx < 0) {
        mtd_rtn <- 0
        mtd_rtn_yest <- 0
      } else {
        if (acidx_data$base_ccy[iacidx] == 'USD') {
          if (is.na(acidx_data$pct_hdg[iacidx]) || acidx_data$pct_hdg[iacidx] == 0) {
            mtd_rtn_idx <- index_data$mtd_rtn_usd[iidx]
            mtd_rtn_yest_idx <- index_data$mtd_rtn_yest_usd[iidx]
          } else {
            mtd_rtn_idx <- index_data$mtd_rtn_usd_h[iidx]
            mtd_rtn_yest_idx <- index_data$mtd_rtn_yest_usd_h[iidx]
          }
        } else {
          if (is.na(acidx_data$pct_hdg[iacidx]) || acidx_data$pct_hdg[iacidx] == 0) {
            mtd_rtn_idx <- index_data$mtd_rtn_gbp[iidx]
            mtd_rtn_yest_idx <- index_data$mtd_rtn_yest_gbp[iidx]
          } else {
            mtd_rtn_idx <- index_data$mtd_rtn_gbp_h[iidx]
            mtd_rtn_yest_idx <- index_data$mtd_rtn_yest_gbp_h[iidx]
          }
        }
        mtd_rtn <- acidx_data$index_wt[iacidx] * as.numeric(mtd_rtn_idx)
        mtd_rtn_yest <- acidx_data$index_wt[iacidx] * as.numeric(mtd_rtn_yest_idx)
      }
    } else {
      if (iidx > 0) {
        if (acidx_data$base_ccy[iacidx] == 'USD') {
          if (is.na(acidx_data$pct_hdg[iacidx]) || acidx_data$pct_hdg[iacidx] == 0) {
            mtd_rtn_idx <- index_data$mtd_rtn_usd[iidx]
            mtd_rtn_yest_idx <- index_data$mtd_rtn_yest_usd[iidx]
          } else {
            mtd_rtn_idx <- index_data$mtd_rtn_usd_h[iidx]
            mtd_rtn_yest_idx <- index_data$mtd_rtn_yest_usd_h[iidx]
          }
        } else {
          if (is.na(acidx_data$pct_hdg[iacidx]) || acidx_data$pct_hdg[iacidx] == 0) {
            mtd_rtn_idx <- index_data$mtd_rtn_gbp[iidx]
            mtd_rtn_yest_idx <- index_data$mtd_rtn_yest_gbp[iidx]
          } else {
            mtd_rtn_idx <- index_data$mtd_rtn_gbp_h[iidx]
            mtd_rtn_yest_idx <- index_data$mtd_rtn_yest_gbp_h[iidx]
          }
        }
        mtd_rtn <- mtd_rtn + acidx_data$index_wt[iacidx] * as.numeric(mtd_rtn_idx)
        mtd_rtn_yest <- mtd_rtn_yest + acidx_data$index_wt[iacidx] * as.numeric(mtd_rtn_yest_idx)
      }
    }
  }
  day_rtn = 100 * ((1 + mtd_rtn/100)/(1 + mtd_rtn_yest/100) - 1)
  ac_data[nac,] <- c(acidx_data$account_id[nacidx], mtd_rtn, mtd_rtn_yest, day_rtn, acidx_data$calc_eom[nacidx])
}
```

```{r ReadDB, include=FALSE}
if (nac > 0) {
  query_text <- paste0("SELECT account_id, source, obs_date, account_index, bench_index
    FROM caim_account_performance cap
    WHERE cap.obs_date >= '",params$dt_eff-7,"'
    AND cap.obs_date <= '",params$dt_eff,"'
    AND source = 'OFF'
    AND period = 'D'
    ORDER BY account_id, source, obs_date")
  past_data <- data.table(caim::mdb_get(conn, query_text))
  nPast <- length(past_data$account_id)
}
```

```{r ReadEOMDB, include=FALSE}
if (nac > 0 && EndOfMonth(params$dt_eff)) {
  dtEOM <- ceiling_date(params$dt_eff, 'month') %m-% days(1)
  query_text <- paste0("SELECT account_id, source, obs_date, account_index, bench_index
    FROM caim_account_performance cap
    WHERE cap.obs_date >= '",dtEOM-47,"'
    AND cap.obs_date <= '",dtEOM,"'
    AND source = 'OFF'
    AND period = 'M'
    ORDER BY account_id, source, obs_date")
  past_eom_data <- data.table(caim::mdb_get(conn, query_text))
  nPastEOM <- length(past_eom_data$account_id)
}
```

```{r WriteDB, include=FALSE}
nac <- length(ac_data$account_id)
if (nac > 0) {
  nadd <- 0
  add_data <- data.frame(matrix(nrow=0,ncol=7))
  names(add_data)<-c("account_id","obs_date","source","period","account_index","bench_return","bench_index")
  
  for (iac in 1:nac) {
    if (!is.na(ac_data$day_rtn[iac])) {
      
      #check if pre-existing perf record
      past_ac <- GetPastAc(ac_data$account_id[iac], params$dt_eff, past_data, nPast)
      
      if (past_ac[1]) {
        #if no record exists then need to create one
        nadd <- nadd + 1
        add_data[nadd,1] <- ac_data$account_id[iac]
        add_data[nadd,2] <- format(params$dt_eff,"%Y-%m-%d")
        add_data[nadd,3] <- "OFF"
        add_data[nadd,4] <- "D"
        add_data[nadd,5] <- past_ac[2]
        add_data[nadd,6] <- ac_data$day_rtn[iac]
        add_data[nadd,7] <- past_ac[3] * (1 + as.numeric(ac_data$day_rtn[iac])/100)
      } else {
        #if a record exits then update it
        #!!! using REAL table
        upd_text <- paste0("UPDATE caim_account_performance
            SET bench_return = ", ac_data$day_rtn[iac],
                             ",bench_index = ", past_ac[3] * (1 + as.numeric(ac_data$day_rtn[iac])/100),
                             " WHERE account_id = '", ac_data$account_id[iac],"'
            AND obs_date = '",params$dt_eff, "'
            AND source = 'OFF'
            AND period = 'D'")
        caim::mdb_execute(conn, upd_text)
      }
    }
  }
  
  if (nadd > 0) {
    #!!! using REAL table
    caim::mdb_insert(conn, "caim_account_performance", add_data)
  }
}
```

```{r WriteEOMDB, include=FALSE}
if (EndOfMonth(params$dt_eff)) {
  
  nac <- length(ac_data$account_id)
  if (nac > 0) {
    nadd_eom <- 0
    add_eom_data <- data.frame(matrix(nrow=0,ncol=7))
    names(add_eom_data)<-c("account_id","obs_date","source","period","account_index","bench_return","bench_index")

    for (iac in 1:nac) {
      
      if (is.na(ac_data$calc_eom[iac])) {
        ac_data$calc_eom[iac] <- "Y"
      }
      
      if (!is.na(ac_data$mtd_rtn[iac]) && toupper(ac_data$calc_eom[iac]) != "N") {
        
        #check if pre-existing perf record
        past_ac <- GetPastAc(ac_data$account_id[iac], dtEOM, past_eom_data, nPastEOM)
        
        #!!!
        if (past_ac[1]) {
          #if no record exists then need to create one
          nadd_eom <- nadd_eom + 1
          add_eom_data[nadd_eom,1] <- ac_data$account_id[iac]
          add_eom_data[nadd_eom,2] <- format(dtEOM,"%Y-%m-%d")
          add_eom_data[nadd_eom,3] <- "OFF"
          add_eom_data[nadd_eom,4] <- "M"
          add_eom_data[nadd_eom,5] <- past_ac[2]
          add_eom_data[nadd_eom,6] <- ac_data$mtd_rtn[iac]
          add_eom_data[nadd_eom,7] <- past_ac[3] * (1 + as.numeric(ac_data$mtd_rtn[iac])/100)
        } else {
          #if a record exits then update it
          #!!! using REAL table
          upd_text <- paste0("UPDATE caim_account_performance
              SET bench_return = ", ac_data$mtd_rtn[iac],
                               ",bench_index = ", past_ac[3] * (1 + as.numeric(ac_data$mtd_rtn[iac])/100),
                               " WHERE account_id = '", ac_data$account_id[iac],"'
              AND obs_date = '",params$dt_eff, "'
              AND source = 'OFF'
              AND period = 'M'")
          # print(upd_text)
          caim::mdb_execute(conn, upd_text)
        }
      }
    }
    
    if (nadd_eom > 0) {
      #!!! using REAL table
      caim::mdb_insert(conn, "caim_account_performance", add_eom_data)
    }
  }
}
```

```{r Housekeeping, include=FALSE}
caim::mdb_disconnect(conn)
```
